---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
build_arg_defaults:
  EE_BASE_IMAGE: "registry-proxy.engineering.redhat.com/rh-osbs/ansible-automation-platform-22-ee-supported-rhel8"
ansible_config: ansible.cfg
additional_build_steps:
  append:
    - RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/awscliv2.zip"
    - RUN unzip /awscliv2.zip -d /aws
    - RUN /aws/aws/install
    - RUN curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "/session-manager-plugin.rpm"
    - RUN dnf install -y /session-manager-plugin.rpm
